[pytest]
addopts = --cov=. --cov-report=term-missing --cov-report=xml --cov-fail-under=20
asyncio_mode = auto

[coverage:run]
omit =
    tests/*
    main.py

[coverage:report]
omit =
    tests/*
    main.py
