[pytest]
addopts = --cov=. --cov-config=pytest.ini --cov-report=term-missing --cov-report=xml --cov-fail-under=60
asyncio_mode = auto

[coverage:run]
omit =
    tests/*
    main.py
    services/s3_service.py
    services/ocr_service.py
    services/llm_service.py
    services/erp_service.py
    repositories/db.py
    repositories/models.py
    repositories/receipt_repo.py
    repositories/receipt_image_repo.py
    routes/receipts.py

[coverage:report]
omit =
    tests/*
    main.py
    services/s3_service.py
    services/ocr_service.py
    services/llm_service.py
    services/erp_service.py
    repositories/db.py
    repositories/models.py
    repositories/receipt_repo.py
    repositories/receipt_image_repo.py
    routes/receipts.py
